<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="NODE1099" name="com.firstTestNG.tests.SampleLoginTest" tests="4" failures="1" timestamp="21 Jul 2019 15:44:04 GMT" time="129.151" errors="0">
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="34.800" classname="com.firstTestNG.tests.SampleLoginTest">
    <skipped/>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
  <testcase name="testUserAbleToBuyPillowSuccessfully_TC01" time="35.677" classname="com.firstTestNG.tests.SampleLoginTest"/>
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="29.736" classname="com.firstTestNG.tests.SampleLoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Retry link is not getting displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Retry link is not getting displayed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.firstTestNG.tests.SampleLoginTest.testUserUnAbleToBuyPillow_TC02(SampleLoginTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="28.938" classname="com.firstTestNG.tests.SampleLoginTest">
    <skipped/>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
</testsuite> <!-- com.firstTestNG.tests.SampleLoginTest -->
